# Data Encoding

Nominal means: Categories with NO order/ranking.
 * Examples : Country names, Blood groups
 * Using in One-Hot Encoding

Ordinal means: Categories WITH meaningful order/ranking.
* Using in Ordinal Encoding
* Example : | Size   |
| ------ |
| Small  |
| Medium |
| Large  |

### Ordinal Encoding

In [1]:
import numpy as np
import seaborn as sns
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

In [2]:
df = pd.read_csv("customer.csv")

df.sample(5)

    age  gender   review education purchased
29   83  Female  Average        UG       Yes
33   89  Female     Good        PG       Yes
18   19    Male     Good    School        No
36   34  Female     Good        UG       Yes
0    30  Female  Average    School        No

In [16]:
df = df.iloc[:,2:]
df.head(15)

   purchased
0         No
1         No
2         No
3         No
4         No
5        Yes
6         No
7        Yes
8         No
9        Yes
10       Yes
11       Yes
12        No
13        No
14       Yes

In [4]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1], test_size=0.2)

In [7]:
x_train

     review education
14     Poor        PG
28     Poor    School
34  Average    School
0   Average    School
40     Good    School
4   Average        UG
33     Good        PG
19     Poor        PG
7      Poor    School
44  Average        UG
42     Good        PG
39     Poor        PG
10     Good        UG
16     Poor        UG
2      Good        PG
47     Good        PG
37  Average        PG
1      Poor        UG
13  Average    School
6      Good    School
49     Good        UG
15     Poor        UG
41     Good        PG
27     Poor        PG
30  Average        UG
25     Good    School
26     Poor        PG
36     Good        UG
35     Poor    School
48     Good        UG
38     Good    School
23     Good    School
24  Average        PG
11     Good        UG
8   Average        UG
29  Average        UG
5   Average    School
9      Good        UG
46     Poor        PG
12     Poor    School

In [8]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'], ['School', 'UG', 'PG']])

In [9]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [10]:
x_train = oe.transform(x_train)
x_test = oe.transform(x_test)

In [11]:
x_train

array([[0., 2.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [2., 0.],
       [1., 1.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [1., 1.],
       [2., 2.],
       [0., 2.],
       [2., 1.],
       [0., 1.],
       [2., 2.],
       [2., 2.],
       [1., 2.],
       [0., 1.],
       [1., 0.],
       [2., 0.],
       [2., 1.],
       [0., 1.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [2., 0.],
       [0., 2.],
       [2., 1.],
       [0., 0.],
       [2., 1.],
       [2., 0.],
       [2., 0.],
       [1., 2.],
       [2., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [2., 1.],
       [0., 2.],
       [0., 0.]])

### Label Encoding

In [12]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

le.fit(y_train)

y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [15]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [13]:
y_train

array([1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0])

### One-Hot Encoding

In [4]:
df= pd.read_csv("cars.csv")

df.head(5)

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [18]:
df["brand"].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Kia                 4
Ambassador          4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [20]:
df["brand"].nunique()

32

#### 1. One-Hot Encoding Using pandas

In [6]:
pd.get_dummies(df, columns=["fuel", "owner"])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

#### 2. K-1 One-Hot Encoding

In [7]:
pd.get_dummies(df, columns=["fuel", "owner"],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

#### 3. One-Hot Encoding using Sklearn

In [ ]:
# Import function to split dataset into training and testing data
from sklearn.model_selection import train_test_split

# Import One Hot Encoder for converting categorical data into numerical form
from sklearn.preprocessing import OneHotEncoder

# Split dataset into:
# x -> input features
# y -> target/output column

# df.iloc[:,0:4]  -> selecting columns from index 0 to 3 as input features
# df.iloc[:,-1]   -> selecting last column as target variable

# test_size=0.2   -> 20% data used for testing
# random_state=2  -> ensures same random split every time

x_train, x_test, y_train, y_test = train_test_split(
    df.iloc[:,0:4],
    df.iloc[:,-1],
    test_size=0.2,
    random_state=2
)

# Create OneHotEncoder object

# drop="first"
# Removes first category to avoid Dummy Variable Trap
# Example:
# Fuel = Petrol, Diesel
# Only one column needed because second can be understood automatically

# sparse=False
# Returns normal NumPy array instead of sparse matrix

ohe = OneHotEncoder(
    drop="first",
    sparse_output=False
)

# Fit encoder on training data and transform categorical columns

# fit_transform():
# 1. Learns categories from training data
# 2. Converts categories into encoded numerical columns

# Encoding columns:
# owner and fuel

x_train_new = ohe.fit_transform(
    x_train[["owner", "fuel"]]
)

# Transform testing data using already learned categories

# IMPORTANT:
# We use only transform() on test data
# because model should learn ONLY from training data

x_test_new = ohe.transform(
    x_test[["fuel", "owner"]]
)

# Combine numerical columns with encoded categorical columns

# x_train[["brand","km_driven"]].values
# Selecting numerical/non-encoded columns

# np.hstack()
# Horizontally combines arrays column-wise

final_train_data = np.hstack((
    x_train[["brand", "km_driven"]].values,
    x_train_new
))

# Print final processed training data
print(final_train_data)

#### 4. OneHotEncoding with Top Categories

In [ ]:
# Count frequency of each unique brand
count = df["brand"].value_counts()

# Find number of unique brands
df["brand"].nunique()

# Set threshold value
# Brands having frequency <= 100 will be replaced
threshold = 100

# Select brands whose count is less than or equal to threshold
replace = count[count <= threshold].index

# Replace low-frequency brands with "other"
# Then apply One Hot Encoding using get_dummies()

encoded_data = pd.get_dummies(
    df["brand"].replace(replace, "other")
)

# Display encoded dataframe
print(encoded_data)

# Column Transformer

In [7]:
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split

In [4]:
df = pd.read_csv("covid_toy.csv")

df.sample(5)

    age  gender  fever   cough       city has_covid
15   70    Male  103.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
8    19  Female  100.0  Strong  Bangalore        No
71   75  Female  104.0  Strong      Delhi        No
17   40  Female   98.0  Strong      Delhi        No

In [ ]:
df["city"].value_counts()

# gender -> One-Hot Encoding
# fever -> SimpleImputer
# cough -> ordinal Encoding 
# city -> OneHotEncoder
# has_covid -> LabelEncoder

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [12]:
x_train, x_test, y_train, y_test = train_test_split(df.drop(columns=["has_covid"]), df['has_covid'], test_size=0.2)
x_train

    age  gender  fever   cough       city
58   23    Male   98.0  Strong     Mumbai
65   69  Female  102.0    Mild  Bangalore
94   79    Male    NaN  Strong    Kolkata
75    5    Male  102.0    Mild    Kolkata
15   70    Male  103.0  Strong    Kolkata
..  ...     ...    ...     ...        ...
29   34  Female    NaN  Strong     Mumbai
44   20    Male  102.0  Strong      Delhi
11   65  Female   98.0    Mild     Mumbai
28   16    Male  104.0    Mild    Kolkata
61   81  Female   98.0  Strong     Mumbai

[80 rows x 5 columns]

In [14]:
si = SimpleImputer()
x_train_fever = si.fit_transform(x_train[["fever"]])
x_test_fever = si.fit_transform(x_test[["fever"]])

In [17]:
oe = OrdinalEncoder(categories=[["Mild","Strong"]])
x_train_cough = oe.fit_transform(x_train[["cough"]])
x_test_cough = oe.fit_transform(x_test[["cough"]])
x_train_cough.shape

(80, 1)

In [22]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop="first", sparse_output=False)
x_train_city_gender = ohe.fit_transform(x_train[["city", "gender"]])
x_test_city_gender = ohe.fit_transform(x_test[["city", "gender"]])

In [23]:
x_train_age = x_train.drop(columns=["gender", "city", "cough", "fever"]).values
x_test_age = x_test.drop(columns=["gender", "city", "cough", "fever"]).values

In [25]:
x_train_transformed = np.concatenate((x_train_city_gender, x_train_age, x_train_fever, x_train_cough),axis=1)
x_test_transformed = np.concatenate((x_test_age,x_test_city_gender,x_test_cough, x_test_fever),axis=1)

#### Now using Column transformer

In [26]:
from sklearn.compose import ColumnTransformer

In [31]:
transformer = ColumnTransformer(transformers=[
    ("tnf1",SimpleImputer(), ["fever"]),
    ("tnf2",OrdinalEncoder(categories=[["Mild", "Strong"]]),["cough"]),
    ("tnf3", OneHotEncoder(sparse_output=False, drop="first"),["gender", "city"])
],remainder="passthrough")

In [33]:
transformer.fit_transform(x_train).shape

(80, 7)

In [34]:
transformer.transform(x_test).shape

(20, 7)