In [355]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.tree import DecisionTreeClassifier

In [356]:
df = pd.read_csv("./titanic/train.csv")

In [357]:
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
459,460,0,3,"O'Connor, Mr. Maurice",male,NaN,0,0,371060,7.7500,NaN,Q
379,380,0,3,"Gustafsson, Mr. Karl Gideon",male,19.0,0,0,347069,7.7750,NaN,S
455,456,1,3,"Jalsevac, Mr. Ivan",male,29.0,0,0,349240,7.8958,NaN,C
675,676,0,3,"Edvardsson, Mr. Gustaf Hjalmar",male,18.0,0,0,349912,7.7750,NaN,S
573,574,1,3,"Kelly, Miss. Mary",female,NaN,0,0,14312,7.7500,NaN,Q

In [358]:
df.drop(columns=["PassengerId", "Name","Ticket", "Cabin"], inplace=True)

In [359]:
# Step 1 = Split train and test
x_train, x_test, y_train, y_test = train_test_split(df.drop(columns=["Survived"]), df["Survived"], test_size=0.2, random_state=42)

In [360]:
x_train.head()

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
331       1    male  45.5      0      0  28.5000        S
733       2    male  23.0      0      0  13.0000        S
382       3    male  32.0      0      0   7.9250        S
704       3    male  26.0      1      0   7.8542        S
813       3  female   6.0      4      2  31.2750        S

In [361]:
trf1 = ColumnTransformer([
    ("impute_age", SimpleImputer(), [2]),
    ("impute_embarked", SimpleImputer(strategy="most_frequent"), [6])
], remainder="passthrough")

In [362]:
# one hot encoding
trf2 = ColumnTransformer([
    ("ohe_sex_embarked",
     OneHotEncoder(sparse_output=False, handle_unknown="ignore"),
     [1, 6])
], remainder="passthrough")

In [363]:
# Scalling 
trf3 = ColumnTransformer([
    ("scale", MinMaxScaler(), slice(0,10))
],remainder="passthrough")

In [364]:
# Feature Selection
trf4 = SelectKBest(score_func=chi2,k=5)

In [365]:
# train the model
trf5 = DecisionTreeClassifier()

In [366]:
# Create Pipeline

pipe = Pipeline([
    ("trf1", trf1),
    ("trf2", trf2),
    ("trf3", trf3),
    ("trf4", trf4),
    ("trf5", trf5),
])

In [367]:
# Alternative syntax
# pipe= make_pipeline(trf1,trf2,trf3,trf4,trf5)

In [ ]:
#train
pipe.fit(x_train, y_train)

ValueError: could not convert string to float: 'male'